### ISSUE TITLE
demo data failing to upload to GCS

### ISSUE THREAD

**Issue by sanjaykhobragade** [GoogleCloudPlatform/healthcare#119]
Uploading generated data to GCS using below command is failing:
gsutil -u ${PROJECT_ID?} cp demo_data.ndjson gs://${PROJECT_ID?}/demo_data.ndjson

CommandException: No URLs matched: demo_data.ndjson

FYI, the previous command completed successfully for me:
bazel run //datagen:data_gen -- --num=1 --output_path=demo_data.ndjson

**Comment by nikklassen** [comment]
Bazel doesn't run in the current directory. Your output file was generated in a subdirectory of bazel-out. I recommend updating your output_path to include the working directory. i.e.
`bazel run //datagen:data_gen -- --num=1 --output_path=$PWD/demo_data.ndjson`

**Comment by sanjaykhobragade** [comment]
that worked. Thanks!
