### ISSUE TITLE
FHIR Immunizations Demo README clarification needed

### ISSUE THREAD

**Issue by sanjaykhobragade** [GoogleCloudPlatform/healthcare#120]
It says "You will also need to register http://localhost:4200/oauth-callback as an authorized redirect URI on the OAuth configuration page. " 

The issue is I couldn't find option to do this on the OAuth configuration page. More clarifying details on this would help.

**Comment by nikklassen** [comment]
Thanks for your feedback. You're right, this screen is hard to find. For reference, it's "APIs & Services" > Credentials > your OAuth 2.0 client ID > Restrictions. I'll update the documentation to clarify how to find this option.

**Comment by sanjaykhobragade** [comment]
Thanks for your response!
I am not seeing "Restrictions" option anywhere on OAuth 2.0 client IDs screen. 
I have edit, delete and download options on Credentials screen and download json, reset secret and delete options if I select a client id.

**Comment by nikklassen** [comment]
When you click into you client ID you should see these two sections. ![Add it here](https://user-images.githubusercontent.com/3314933/59625855-58609000-9108-11e9-876f-9a8dd2e4835b.png)

**Comment by nikklassen** [comment]
Closed in #123
