### ISSUE TITLE
Healthcare APIs accessible through Firebase?

### ISSUE THREAD

**Issue by sanjaykhobragade** [GoogleCloudPlatform/healthcare#126]
I have this question and wasn't sure what the right forum to ask so trying my luck here.

Can I access healthcare APIs through Firebase functions?

**Comment by nikklassen** [comment]
My understanding is that using Firebase functions should be the same as using Cloud Functions. You can see an example of how to do this [here](https://github.com/GoogleCloudPlatform/healthcare/blob/master/fhir/lung-cancer/inference/main.py). This is a script that runs in a Cloud Function and retrieves data from the FHIR store. If this doesn't work please let me know any further issues you run into.
