### ISSUE TITLE
Reference to non-public dependency

### ISSUE THREAD

**Issue by foumedia** [GoogleCloudPlatform/healthcare#391]
This dependency looks like it's a reference to the Google3 monolith. Can we resolve this?

https://github.com/GoogleCloudPlatform/healthcare/blob/f31edecb2fdb7d085cb94427ae5a27abba540314/deploy/cmd/apply/apply.go#L41

**Comment by paulchurch** [comment]
Looks like the dependency didn't get rewritten correctly. I'll chase this down.

**Comment by nikklassen** [comment]
Fixed in #394
