### ISSUE TITLE
Facing error "socket hang up" while calling dicomWebStoreInstance through Firebase cloud functions

### ISSUE THREAD

**Issue by nehawankar174** [GoogleCloudPlatform/healthcare#396]
Hello,

I am trying to run DICOMweb healthcare API for **dicomWebStoreInstance** using **Firebase cloud functions**, it's throwing the following error:

request to _https://healthcare.googleapis.com/v1beta1/projects/........../dicomWeb/studies_ failed, reason: socket hang up

For the same I increased timeout period upto 5 min, still got the same error. 

Also, I have tried to call the same API with client-server approach in my local system, it works successfully with proper response.

Can anyone suggest why this API is not working with the Firebase cloud functions.
Any help regarding this would be greatly appreciated!

Thanks

**Comment by dzelemba** [comment]
Any luck getting this to work?

**Comment by dzelemba** [comment]
I'm going to close this issue as obsolete, but feel free to re-open if you're still having trouble.
