### ISSUE TITLE
"Kubernetes Cluster and a Deployment for the inference module" step is failing in breast_density_auto_ml.ipynb

### ISSUE THREAD

**Issue by sanjaykhobragade** [GoogleCloudPlatform/healthcare#400]
Its failing with the below error:
I believe the failure is due to the location in the notebook is defined as = "us-central1".
But for Kubernetes Cluster creation, you would have to select region and zone like "us-central1-a" which is not acceptable in Healthcare APIs since currently healthcare dataset can be created only in a region not in a region/zone.

WARNING: In June 2019, node auto-upgrade will be enabled by default for newly created clusters and node pools. To disable it, use the `--no-enable-autoupgrade` flag.
WARNING: Starting in 1.12, new clusters will have basic authentication disabled by default. Basic authentication can be enabled (or disabled) manually using the `--[no-]enable-basic-auth` flag.
WARNING: Starting in 1.12, new clusters will not have a client certificate issued. You can manually enable (or disable) the issuance of the client certificate using the `--[no-]issue-client-certificate` flag.
WARNING: Currently VPC-native is not the default mode during cluster creation. In the future, this will become the default mode and can be disabled using `--no-enable-ip-alias` flag. Use `--[no-]enable-ip-alias` flag to suppress this warning.
WARNING: Starting in 1.12, default node pools in new clusters will have their legacy Compute Engine instance metadata endpoints disabled by default. To create a cluster with legacy instance metadata endpoints disabled in the default node pool, run `clusters create` with the flag `--metadata disable-legacy-endpoints=true`.
WARNING: Your Pod address range (`--cluster-ipv4-cidr`) can accommodate at most 1008 node(s). 
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
ERROR: (gcloud.container.clusters.create) ResponseError: code=403, message=**Permission denied on 'locations/{location}' (or it may not exist).**
Unable to connect to the server: dial tcp 104.154.119.220:443: i/o timeout

**Comment by codezizo** [comment]
Please let me know if this issue is still occurring for you. This should have been addressed in the recent updates. #450

**Comment by sanjaykhobragade** [comment]
@codezizo  This is working now.
