### ISSUE TITLE
bigquery-json.googleapis.com is not a valid API in new terraform version

### ISSUE THREAD

**Issue by ashkon-mendel** [GoogleCloudPlatform/healthcare#401]
When running:

`bazel run cmd/apply:apply -- --config_path=<config_file_path> --enable_terraform`

I get the error:

_Error: expected service to not match any of [dataproc-control.googleapis.com source.googleapis.com stackdriverprovisioning.googleapis.com bigquery-json.googleapis.com], got bigquery-json.googleapis.com_

Please check [this line](https://github.com/terraform-providers/terraform-provider-google/blob/03cf878c8f8c6367354d3d0657a102a019172d28/google/resource_google_project_service.go#L20) in the terraform-provider-google Github repository for the reason why.

I fixed it locally by changing "bigquery-json.googleapis.com" to "bigquery.googleapis.com" [here](https://github.com/GoogleCloudPlatform/healthcare/blob/f42f8e1abbccbb9793945c2ad5290950f57ce900/deploy/config/terraform.go#L101).

However, I only fixed this locally and I don't know if this problem extends beyond the deployment scripts.

**Comment by umairidris** [comment]
Thanks for pointing this out @ashkon-mendel and sorry for the delay in getting back to you. We have fixed this: https://github.com/GoogleCloudPlatform/healthcare/commit/cb7c28c1f0d9aae17aa709e61c876bba20ab4f39.
