### ISSUE TITLE
imaging/ml  Switch to using our hosted CBIS-DDSM dataset instead of downloading it from TCIA

### ISSUE THREAD

**Issue by pavertomato** [GoogleCloudPlatform/healthcare#433]
based on https://github.com/GoogleCloudPlatform/healthcare/pull/423

- switch from gcs storage to hcapi hosted data
- remove redundant TCIA api code
- `gcloud beta healthcare dicom-stores export` instead of api call
- should be exported only train images that label breast density 2 or 3, avoid filter blacklisted dicoms

**Comment by pavertomato** [comment]
>gcloud beta healthcare dicom-stores export instead of api call

@sadeel 
gcloud and api call to export does not support filtering or export of single object, so we have two options:

- export whole store and try to filter jpegs on gcs
- requesting download each dicom separately by api calls to https://healthcare.googleapis.com/v1beta1/projects/chc-tcia/locations/us-central1/datasets/cbis-ddsm/dicomStores/cbis-ddsm/dicomWeb/studies/XYZ with specifying 'Accept': 'multipart/related; type="image/jpeg"; transfer-syntax=1.2.840.10008.1.2.4.50'

**Comment by sadeel** [comment]
I prefer first option, we want clients to use bulk operations such as ExportDicomData in such cases.

I think you might run into issues mapping the jpegs on gcs to the TCIA provided CSV...if you do feel free to store the mapping somewhere in the repo...perhaps as a static CSV

**Comment by pavertomato** [comment]
> I think you might run into issues mapping the jpegs on gcs to the TCIA provided CSV...if you do feel free to store the mapping somewhere in the repo...perhaps as a static CSV

since export generates folder structure by ids of dcms: `/1.3.6.1.4.1.9590.100.1.2.100052171312354035019149694722933145864/1.3.6.1.4.1.9590.100.1.2.122021886313853636738943991213171853079/1.3.6.1.4.1.9590.100.1.2.143025478211711725141987429563024371610.jpg` i think it will be possible to filter them without additional data

**Comment by pavertomato** [comment]
@sadeel 
i've faced problem with managing access to https://healthcare.googleapis.com/v1beta1/projects/chc-tcia/locations/us-central1/datasets/cbis-ddsm/dicomStores/cbis-ddsm 
old service account may trigger export command, this account was created before our project got access to chc-tcia 
but if i create new service account(with same permissions) and try to run export command i'll get permission error.
So access seems to be managed by CHC-API team, or i haven't found settings  for this.

**question:** should README says that user should communicate with CHC-API team to grant permissions to service account or we have any additional way to get such permissions for service account?

**Comment by sadeel** [comment]
Yes, the readme should ask the user to request access for their service account using the form here:
https://cloud.google.com/healthcare/docs/resources/public-datasets/tcia#cloud-healthcare-api

We don't have good support for service accounts right now, I have filed a request internally to handle this. In the mean time, can we ask the user to request access using their email? Then, in the codelab, have the client authenticate using their email before doing ExportDicomData?

**Comment by pavertomato** [comment]
>Then, in the codelab, have the client authenticate using their email before doing ExportDicomData?

seems like `gcloud init --console-only` have only interactive mode for personal accounts so i'll have to put it into README, is it ok?

**Comment by sadeel** [comment]
That sounds fine. This should be a intermediate thing, we'll fix service account access eventually...

**Comment by pavertomato** [comment]
> That sounds fine. This should be a intermediate thing, we'll fix service account access eventually...

readme has been updated

**Comment by sadeel** [comment]
fixed in latest commit
