### ISSUE TITLE
Installing google-cloud-automl in breast_density_auto_ml.ipynb

### ISSUE THREAD

**Issue by sanjaykhobragade** [GoogleCloudPlatform/healthcare#458]
**!sudo pip3 install google-cloud-automl** did not work for me.
It was giving me error about not able to find automl module.

I had to instead use
!python3 -m pip install google-cloud-automl

which fixed the issue for me. This is just an FYI...if others come across same issue.

**Comment by codezizo** [comment]
@sanjaykhobragade did you create a Python3 Notebook? It should have pip3 installed. Can you please run `!pip -V` and `!pip3 -V`.

**Comment by sanjaykhobragade** [comment]
Yes, I have a Python3 Notebook.Here's the values:
!pip -V
pip 20.0.2 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
!pip3 -V
pip 20.0.2 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)

**Comment by codezizo** [comment]
This should address the issue: 75f6d9f
