### ISSUE TITLE
Question on imaging/ml/ml_codelab/scripts/inference/inference.py file

### ISSUE THREAD

**Issue by sanjaykhobragade** [GoogleCloudPlatform/healthcare#459]
What's the purpose of below code in healthcare/imaging/ml/ml_codelab/scripts/inference/inference.py file ?

if not parsed_message:
      _logger.info('Ignoring new message: %s', image_instance_path)
      message.ack()
      return

Why the message is being acknowledged even though the message is being ignored? I would imaging message to be acknowledged after it has been processed successfully.

**Comment by codezizo** [comment]
So this is because if the message is invalid it should be ack()'d since it was technically processed by the inference module and if we don't ack() it will be re-delivered after the ack deadline. https://cloud.google.com/pubsub/docs/subscriber#delivery.
