### ISSUE TITLE
var.composite_root_resources is null

### ISSUE THREAD

**Issue by xingziye** [GoogleCloudPlatform/healthcare#462]
Hi,

I have encoutnered this issue when deploy a forseti project.
```
Error: Invalid function argument

  on external/terraform_google_forseti/modules/server_config/main.tf line 31, in locals:
  31:   root_resource_id         = "root_resource_id: ${length(var.composite_root_resources) > 0 ? "\"\"" : var.folder_id != "" ? "folders/${var.folder_id}" : "organizations/${var.org_id}"}"
    |----------------
    | var.composite_root_resources is null

Invalid value for "value" parameter: argument must not be null.


Error: Invalid function argument

  on external/terraform_google_forseti/modules/server_config/main.tf line 32, in locals:
  32:   composite_root_resources = length(var.composite_root_resources) > 0 ? "composite_root_resources: [${join(", ", formatlist("\"%s\"", var.composite_root_resources))}]" : ""
    |----------------
    | var.composite_root_resources is null

Invalid value for "value" parameter: argument must not be null.
```
but I also noticed that in the config schema, you mentioned composite_root_resources should be unset.
Can I please have some help on what should I specify there? Thank you!

**Comment by xingao267** [comment]
@xingziye Do you have `organization_id` and/or `folder_id` set in your DPT configs?  [example](https://github.com/GoogleCloudPlatform/healthcare/blob/master/deploy/samples/full/shared.yaml#L8). DPT will automatically configure the `composite_root_resources` for forseti using those values. https://github.com/GoogleCloudPlatform/healthcare/blob/master/deploy/config/config.go#L263

**Comment by xingziye** [comment]
@xingao267 Thank you for your help! I assume that is the issue. What if I don't have an organization_id nor a folder_id? All my projects are created under 'No organization id:0', can I still setup without an organization?

**Comment by xingao267** [comment]
@xingziye Right now, the toolkit does not support setting up Forseti without giving an `organization_id` or a `folder_id`.

Do you need Forseti? You could still use the toolkit to set up GCP projects with auditing but not using the monitoring part (Forseti), which is what we typically recommend users at the beginning as Forseti requires maintenance and development of monitoring policies. If you simply want to stand up few GCP projects with storage, healthcare datasets, bigquery, proper iam bindings, etc, you don't need Forseti.
