### ISSUE TITLE
What is this repo vs. the https://github.com/google/fhir repo? and how to generate clients?

### ISSUE THREAD

**Issue by deanorderly** [GoogleCloudPlatform/healthcare#464]
I can use artman to generate clients in googleapis repo but can't seem to do that in the google/fhir repo.  What is this repo?  How is all this related?  

I am trying to get maven central artifacts for google healthcare api OR generate my own java objects but can't seem to find anything.

thanks for ANY pointers!!!  I have been draining huge amounts of time today in this.

**Comment by nikklassen** [comment]
This repo is a collection of demos and example projects that use the Cloud Healthcare API, in addition to the Cloud Healthcare Data Protection Toolkit. I saw your request on the google/fhir repo, I think that's where you want to be looking. I don't know why that repo doesn't have issues set up, I'm going to look into getting that resolved.

Regarding client libraries, you can find more information about the ones that we publish [here](https://cloud.google.com/apis/docs/client-libraries-explained)

**Comment by deanorderly** [comment]
thanks much @nikklassen !!! really appreciated.  Any way I can get a build command in that repo to build JUST this picture of FHIR...  https://build.fhir.org/ig/HL7/davinci-pdex-plan-net/index.html

We are trying to build just a section of FHIR.  I managed to run "bazel build //java:json_format" but that built everyting I think in FHIR as it resulted in 680MB of 600 jars :(.   I would like to scale down to just that section of healthcare.

Or anyway I can be put in touch with someone that might know or hopefully if issues are setup I can post my question there on that project.

thanks again!!!

**Comment by deanorderly** [comment]
no worries, thanks for pinging the team!!!!

Dean

**Comment by nikklassen** [comment]
Recently the google/fhir repo fixed to allow issues to be filed there. I encourage you to reach out to that team directly.
