### ISSUE TITLE
IAM group can't be assigned owner role

### ISSUE THREAD

**Issue by brunodd** [GoogleCloudPlatform/healthcare#471]
When running the simple configuration, the owner-group is attempted to be set as project owner which isn't possible.

```
  # google_project_iam_member.project["roles/owner group:my-group@googlegroups.com"] will be created
  + resource "google_project_iam_member" "project" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + member  = "group:my-group@googlegroups.com"
      + project = "my-test-project-000"
      + role    = "roles/owner"
    }
```

**Comment by umairidris** [comment]
Could you explain why it isn't possible? You should be able to set additional owners on a project with sufficient permission (e.g. the project creator does it).

I would encourage you to look our next iteration and give that a shot instead: https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite
