### ISSUE TITLE
deployment of inference module is failing in breast_density_auto_ml.ipynb

### ISSUE THREAD

**Issue by ankitdata** [GoogleCloudPlatform/healthcare#475]
I am using python3 
all required API's are Enable

WARNING: Currently VPC-native is not the default mode during cluster creation. In the future, this will become the default mode and can be disabled using `--no-enable-ip-alias` flag. Use `--[no-]enable-ip-alias` flag to suppress this warning.
WARNING: Newly created clusters and node-pools will have node auto-upgrade enabled by default. This can be disabled using the `--no-enable-autoupgrade` flag.
WARNING: Starting with version 1.18, clusters will have shielded GKE nodes by default.
WARNING: Your Pod address range (`--cluster-ipv4-cidr`) can accommodate at most 1008 node(s). 
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
**ERROR: (gcloud.container.clusters.create) ResponseError: code=403, message=Permission denied on 'locations/{location}' (or it may not exist).**
Error from server (NotFound): the server could not find the requested resource

_**solution on this similar issue https://github.com/GoogleCloudPlatform/healthcare/issues/400#issue-526711247 not working for me**_.

@codezizo

**Comment by codezizo** [comment]
@ankitdata is this issue happening when you are running `gcloud container clusters create inference-module --region=$2 --scopes https://www.googleapis.com/auth/cloud-platform --num-nodes=1` if so can you make sure all the variables are set correctly, specifically the **location** variable?

**Comment by ankitdata** [comment]
yes all variable are correctly specified including location variable.

**Comment by codezizo** [comment]
Hi @ankitdata,

can you please try running: 

`gcloud projects add-iam-policy-binding $1 --member=serviceAccount:${COMPUTE_ENGINE_SERVICE_ACCOUNT} --role roles/container.admin`

then running with the location explicitly set: 
`gcloud container clusters create inference-module --region=us-central1 --scopes https://www.googleapis.com/auth/cloud-platform --num-nodes=1`

Let me know if that works. It seems like it is a permission issue.

**Comment by codezizo** [comment]
Closing. Please file a new bug if this isn't resolved.
