### ISSUE TITLE
Ingesting HL7v2 data from GCS failing 

### ISSUE THREAD

**Issue by yobroyem0** [GoogleCloudPlatform/healthcare#477]
Command: 
```
curl -X POST \
     -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
     -H "Content-Type: application/json; charset=utf-8" \
     --data'gcsSource': {
        'uri': 'gs://$(PROJECT_ID)/hl7v2-sample.json'
      } \
     "https://healthcare.googleapis.com/v1/projects/PROJECT_ID/locations/LOCATION/datasets/DATASET_ID/hl7V2Stores/HL7V2_STORE_ID/messages:ingest"
```

Response: 
```
"error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"gcsSource\": Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"gcsSource\": Cannot find field."
          }
        ]
      }
    ]
  }
```

Not sure why it's not able to locate the field. I have also tried using "gcsSourceLocation" and "gcsUri" due to another issue I found [here](https://github.com/GoogleCloudPlatform/healthcare/issues/124), however I still received the same error.

**Comment by paulchurch** [comment]
The gcsSource field is used for import methods - it's not available on ingest.

There is an import method available in the beta API for HL7v2: https://cloud.google.com/healthcare/docs/reference/rest/v1beta1/projects.locations.datasets.hl7V2Stores/import

For ingest examples, see https://cloud.google.com/healthcare/docs/how-tos/hl7v2-messages#ingesting_hl7v2_messages

Hope that helps.
