### ISSUE TITLE
Link to documentation in README is broken

### ISSUE THREAD

**Issue by johngrimes** [GoogleCloudPlatform/healthcare#9]
This link within fhir/immunizations/docs/README.md is broken:

https://cloud.google.com/healthcare/docs/quickstart

**Comment by jack17529** [comment]
@johngrimes repository changed, their is nothing known as "immunizations" now.

**Comment by nikklassen** [comment]
Healthcare docs are now publicly visible so this link shouldn't be an issue anymore.
